/*
 * C64 Commander - Configure and control your Commodore 64 Ultimate over your local network
 * Copyright (C) 2026 Christian Gleissner
 *
 * Licensed under the GNU General Public License v3.0 or later.
 * See <https://www.gnu.org/licenses/> for details.
 */

import { registerPlugin, type PluginListenerHandle } from "@capacitor/core";
import type { NativeTraceContext } from "@/lib/native/nativeTraceContext";
import { getRuntimeFtpPasswordOverride } from "@/lib/ftp/ftpConfig";

export type FtpEntry = {
  name: string;
  path: string;
  type: "file" | "dir";
  size?: number;
  modifiedAt?: string | null;
};

export type FtpListOptions = {
  host: string;
  port?: number;
  username?: string;
  password?: string;
  path?: string;
  timeoutMs?: number;
  connectTimeoutMs?: number;
  traceContext?: NativeTraceContext;
};

export type FtpRecursiveListOptions = FtpListOptions & {
  maxDepth?: number;
  maxEntries?: number;
};

export type FtpRecursiveFailure = {
  path: string;
  message: string;
};

export type FtpReadOptions = {
  host: string;
  port?: number;
  username?: string;
  password?: string;
  path: string;
  timeoutMs?: number;
  connectTimeoutMs?: number;
  traceContext?: NativeTraceContext;
  // Identifies the read so it can emit `ftpReadProgress` events and be cancelled
  // via cancelRead(). Optional — generated by the JS layer when progress/abort is wired.
  requestId?: string;
  // Expected file size (bytes) for progress reporting; 0/absent when unknown.
  totalBytes?: number;
};

export type FtpReadProgressEvent = {
  requestId: string;
  bytesRead: number;
  totalBytes: number;
};

export type FtpWriteOptions = {
  host: string;
  port?: number;
  username?: string;
  password?: string;
  path: string;
  data: string;
  timeoutMs?: number;
  connectTimeoutMs?: number;
  traceContext?: NativeTraceContext;
};

export type FtpPingOptions = {
  host: string;
  port?: number;
  username?: string;
  password?: string;
  connectTimeoutMs?: number;
  traceContext?: NativeTraceContext;
};

export type FtpClientPlugin = {
  listDirectory: (options: FtpListOptions) => Promise<{ entries: FtpEntry[] }>;
  listDirectoryRecursive: (
    options: FtpRecursiveListOptions,
  ) => Promise<{ entries: FtpEntry[]; partialFailures?: FtpRecursiveFailure[]; timedOut?: boolean }>;
  readFile: (options: FtpReadOptions) => Promise<{ data: string; sizeBytes?: number }>;
  writeFile: (options: FtpWriteOptions) => Promise<{ sizeBytes: number }>;
  pingFtp: (options: FtpPingOptions) => Promise<{ ok: boolean }>;
  /** Cancels an in-flight readFile identified by requestId (closes its data stream). */
  cancelRead: (options: { requestId: string }) => Promise<void>;
  addListener: (
    eventName: "ftpReadProgress",
    listenerFunc: (event: FtpReadProgressEvent) => void,
  ) => Promise<PluginListenerHandle>;
};

const rawFtpClient = registerPlugin<FtpClientPlugin>("FtpClient", {
  web: () => import("./ftpClient.web").then((module) => new module.FtpClientWeb()),
});

// While demo mode is active the (now authenticated) mock FTP server requires the
// per-boot token as the FTP password. This is the single funnel every FTP call
// passes through, so injecting it here authenticates all callers without each
// needing to know about the token (HARD10-005). No-op in normal operation
// (override null): the caller's real device password flows through untouched.
const withRuntimeFtpAuth = <T extends { password?: string }>(options: T): T => {
  const override = getRuntimeFtpPasswordOverride();
  return override === null ? options : { ...options, password: override };
};

export const FtpClient: FtpClientPlugin = {
  listDirectory: (options) => rawFtpClient.listDirectory(withRuntimeFtpAuth(options)),
  listDirectoryRecursive: (options) => rawFtpClient.listDirectoryRecursive(withRuntimeFtpAuth(options)),
  readFile: (options) => rawFtpClient.readFile(withRuntimeFtpAuth(options)),
  writeFile: (options) => rawFtpClient.writeFile(withRuntimeFtpAuth(options)),
  pingFtp: (options) => rawFtpClient.pingFtp(withRuntimeFtpAuth(options)),
  cancelRead: (options) => rawFtpClient.cancelRead(options),
  addListener: (eventName, listenerFunc) => rawFtpClient.addListener(eventName, listenerFunc),
};
