analyzer:
  skip_excluded: false

excludes:
  scopes:
    - pattern: "devDependencies"
      reason: "DEV_DEPENDENCY_OF"
      comment: "JavaScript dependencies for development only."
    - pattern: "test.*"
      reason: "TEST_DEPENDENCY_OF"
      comment: "Dependencies used for tests only."
    - pattern: ".*Test.*"
      reason: "TEST_DEPENDENCY_OF"
      comment: "Android / Gradle test dependencies only."
