/*
 * C64 Commander - Configure and control your Commodore 64 Ultimate over your local network
 * Copyright (C) 2026 Christian Gleissner
 *
 * Licensed under the GNU General Public License v3.0 or later.
 * See <https://www.gnu.org/licenses/> for details.
 */

import { defineConfig } from "vite";
import react from "@vitejs/plugin-react-swc";
import istanbul from "vite-plugin-istanbul";
import path from "path";
import fs from "fs";
import { spawnSync } from "child_process";
import { hasInjectedBuildVersion, resolveBuildAppVersion } from "./src/lib/buildVersion";
import { resolveBuildVersionLabel } from "./src/lib/versionLabel";

const pkg = JSON.parse(fs.readFileSync(new URL("./package.json", import.meta.url), "utf-8"));

type RunGitOptions = {
  quiet?: boolean;
  suppressStderrPattern?: RegExp;
};

const runGit = (args: string[], label: string, options: RunGitOptions = {}) => {
  const result = spawnSync("git", args, { encoding: "utf-8" });
  if (result.status === 0) return result.stdout.trim();
  const stderr = result.stderr?.trim() || "";
  const shouldSuppress = Boolean(options.suppressStderrPattern && stderr && options.suppressStderrPattern.test(stderr));
  if (options.quiet || shouldSuppress) return "";
  if (result.error) {
    console.warn(`[build] ${label} failed: ${result.error.message}`);
  } else if (stderr) {
    console.warn(`[build] ${label} failed: ${stderr}`);
  }
  return "";
};

const resolveGitSha = () =>
  process.env.VITE_GIT_SHA ||
  process.env.GIT_SHA ||
  process.env.GITHUB_SHA ||
  runGit(["rev-parse", "HEAD"], "git rev-parse");

const sanitizeBuildToken = (value: string) => value.replace(/[^a-zA-Z0-9._-]+/g, "-");

const resolveAppVersion = () =>
  resolveBuildAppVersion({
    env: process.env,
    packageVersion: pkg.version || "",
  });

// Read the version label generated by scripts/resolve-version.sh (via prebuild).
// Returns an empty string when the file has not been generated yet (e.g. dev mode
// without a prior build, or direct vite invocations that bypass prebuild).
const readGeneratedVersionLabel = (): string => {
  const versionTsPath = path.resolve(__dirname, "src/version.ts");
  try {
    if (!fs.existsSync(versionTsPath)) {
      // No generated version file yet (e.g. dev mode without a prior build).
      return "";
    }
    const content = fs.readFileSync(versionTsPath, "utf-8");
    const m = content.match(/APP_VERSION\s*=\s*'([^']*)'/);
    if (!m) {
      console.warn(
        `[build] ${versionTsPath} exists but APP_VERSION pattern was not found; falling back to git-derived version label.`,
      );
      return "";
    }
    const label = m[1];
    if (!label) {
      console.warn(
        `[build] ${versionTsPath} contains an empty APP_VERSION; falling back to git-derived version label.`,
      );
      return "";
    }
    return label;
  } catch (err) {
    const error = err as NodeJS.ErrnoException;
    if (error && error.code === "ENOENT") {
      // Treat a missing file the same as "not generated yet".
      return "";
    }
    console.warn(
      `[build] Failed to read generated version label from ${versionTsPath}: ${
        (error && error.message) || String(error)
      }`,
    );
    return "";
  }
};

const resolveAppVersionLabel = (gitDescribeValue: string, gitShaValue: string, fallbackVersion: string) => {
  if (hasInjectedBuildVersion(process.env)) {
    return fallbackVersion;
  }
  return resolveBuildVersionLabel({
    generatedVersionLabel: readGeneratedVersionLabel(),
    gitDescribe: gitDescribeValue,
    gitSha: gitShaValue,
    fallbackVersion,
  });
};

const resolveServiceWorkerBuildId = (appVersion: string, gitShaValue: string, buildTimeValue: string) => {
  const envBuildId = process.env.VITE_SW_BUILD_ID || process.env.SW_BUILD_ID || "";
  if (envBuildId) return sanitizeBuildToken(envBuildId);

  const gitShaShort = gitShaValue ? gitShaValue.slice(0, 8) : "";
  const buildTimeToken = buildTimeValue ? sanitizeBuildToken(buildTimeValue.replace(/[:]/g, "-")) : "";
  return [appVersion, gitShaShort || buildTimeToken].filter(Boolean).join("-") || "dev";
};

const gitSha = resolveGitSha();
const gitDescribe =
  process.env.VITE_GIT_DESCRIBE ||
  process.env.GIT_DESCRIBE ||
  runGit(["describe", "--tags", "--long", "--dirty", "--always"], "git describe", {
    quiet: true,
  });
const appVersion = resolveAppVersion();
const appVersionLabel = resolveAppVersionLabel(gitDescribe, gitSha, appVersion);
const buildTime = process.env.VITE_BUILD_TIME || new Date().toISOString();
const serviceWorkerBuildId = resolveServiceWorkerBuildId(appVersion, gitSha, buildTime);
const enableCoverageInstrumentation = ["1", "true"].includes((process.env.VITE_COVERAGE || "").toLowerCase());

// https://vitejs.dev/config/
export default defineConfig(() => ({
  server: {
    host: "::",
    port: 8064,
    hmr: {
      overlay: false,
    },
  },
  assetsInclude: ["**/*.yaml", "**/*.yml"],
  build: {
    outDir: "dist",
    // Adjust warning threshold to avoid noisy chunk warnings while keeping defaults.
    chunkSizeWarningLimit: 1200,
    rollupOptions: {
      output: {
        // Explicit per-domain vendor split. Caps any single chunk at ~250 KB
        // gzipped so the WebView's V8 doesn't spend ~150 ms of cold start
        // parsing one giant blob, and the MimeMap monitor contention from
        // concurrent asset reads is reduced. Enforced by
        // scripts/check-bundle-budgets.mjs.
        manualChunks(id) {
          if (!id.includes("node_modules")) return undefined;
          if (id.includes("/react-router-dom/") || id.includes("/react-router/") || id.includes("/@remix-run/")) {
            return "vendor-router";
          }
          if (id.includes("/@tanstack/")) {
            return "vendor-query";
          }
          if (id.includes("/@radix-ui/")) {
            return "vendor-radix";
          }
          if (id.includes("/framer-motion/") || id.includes("/motion-")) {
            return "vendor-motion";
          }
          if (id.includes("/lucide-react/")) {
            return "vendor-icons";
          }
          if (id.includes("/7z-wasm/") || id.includes("/fflate/")) {
            return "vendor-hvsc";
          }
          // Catch-all UI primitives that aren't in their own bucket but are
          // closely tied to the design system.
          if (id.includes("/class-variance-authority/") || id.includes("/clsx/") || id.includes("/tailwind-merge/")) {
            return "vendor-ui";
          }
          return "vendor-misc";
        },
      },
    },
  },
  plugins: [
    react(),
    ...(enableCoverageInstrumentation
      ? [
          istanbul({
            include: "src/**/*",
            exclude: ["node_modules", "test/", "tests/", "playwright/"],
            extension: [".js", ".ts", ".tsx"],
            requireEnv: true,
            forceBuildInstrument: true,
          }),
        ]
      : []),
  ],
  define: {
    __APP_VERSION__: JSON.stringify(appVersion),
    __APP_VERSION_LABEL__: JSON.stringify(appVersionLabel),
    __GIT_SHA__: JSON.stringify(gitSha),
    __BUILD_TIME__: JSON.stringify(buildTime),
    __SW_BUILD_ID__: JSON.stringify(serviceWorkerBuildId),
  },
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
      module: path.resolve(__dirname, "./src/lib/polyfills/module.ts"),
    },
  },
}));
