appId: uk.gleissner.c64commander
env:
  LONG_TIMEOUT: ${LONG_TIMEOUT || "20000"}
  SHORT_TIMEOUT: ${SHORT_TIMEOUT || "5000"}
  TIMEOUT: ${TIMEOUT || "15000"}
tags:
  - subflow
---
- launchApp:
    stopApp: true
- retry:
    maxRetries: 3
    commands:
      - runFlow:
          when:
            visible: "Continue in Demo Mode"
          file: continue-demo.yaml
      - tapOn:
          text: "Continue in Demo Mode"
          optional: true
      - tapOn:
          text: "Got it"
          optional: true
      - tapOn:
          text: "Wait"
          optional: true
      - tapOn:
          text: "Close app"
          optional: true
      - tapOn:
          text: "Allow"
          optional: true
      - tapOn:
          text: "Allow access"
          optional: true
      - tapOn:
          text: "Allow all the time"
          optional: true
      - tapOn:
          text: "Allow only while using the app"
          optional: true
      - waitForAnimationToEnd
      - tapOn:
          text: "Settings"
          optional: true
      - extendedWaitUntil:
          visible:
            text: "Settings"
          timeout: ${LONG_TIMEOUT}
- tapOn:
    text: "Settings"
    optional: true
- extendedWaitUntil:
    visible: "Settings"
    timeout: ${LONG_TIMEOUT}
- assertVisible: "Settings"
