appId: uk.gleissner.c64commander
env:
  LONG_TIMEOUT: ${LONG_TIMEOUT || "20000"}
  SHORT_TIMEOUT: ${SHORT_TIMEOUT || "5000"}
  TIMEOUT: ${TIMEOUT || "15000"}
tags:
  - subflow
---
- runFlow: launch-and-wait.yaml
- retry:
    maxRetries: 3
    commands:
      - tapOn:
          text: "Settings"
          optional: true
      - tapOn:
          point: "75%,95%"
          optional: true
      - waitForAnimationToEnd
      - extendedWaitUntil:
          visible: "Connection"
          timeout: ${LONG_TIMEOUT}
- extendedWaitUntil:
    visible: "Connection"
    timeout: ${LONG_TIMEOUT}
- assertVisible: "Connection"
