/*
 * C64 Commander - C64 Scope
 * Autonomous testing MCP server for session capture and audio/video verification
 * Copyright (C) 2026 Christian Gleissner
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

import type { CaseDefinition } from "./types.js";
import { testNamespaces } from "./types.js";

export const caseCatalog: CaseDefinition[] = [
  // --- Navigation and Connection (Ready) ---
  {
    id: "nav-route-shell",
    title: "Route shell discovery and tab navigation",
    featureArea: "Navigation",
    route: "/",
    safetyClass: "read-only",
    primaryOracle: "UI tab presence and route transitions",
    fallbackOracle: "Diagnostics/log evidence",
    cleanup: "No cleanup required",
    docRefs: [
      "doc/testing/agentic-tests/agentic-action-model.md",
      "doc/testing/agentic-tests/agentic-feature-surface.md",
    ],
    dependencies: [],
    testability: "ready",
  },
  {
    id: "nav-connection-status",
    title: "Connection status and discovery verification",
    featureArea: "Connection",
    route: "/",
    safetyClass: "read-only",
    primaryOracle: "UI connection indicator plus connection snapshot",
    fallbackOracle: "REST /v1/info reachability evidence",
    cleanup: "No cleanup required",
    docRefs: [
      "doc/testing/agentic-tests/agentic-oracle-catalog.md",
      "doc/testing/agentic-tests/agentic-android-runtime-contract.md",
    ],
    dependencies: ["nav-route-shell"],
    testability: "ready",
  },

  // --- Home (Mixed readiness) ---
  {
    id: "home-readonly-visibility",
    title: "Home page read-only surface visibility",
    featureArea: "Home",
    route: "/",
    safetyClass: "read-only",
    primaryOracle: "UI element presence and values",
    fallbackOracle: "REST-visible device info",
    cleanup: "No cleanup required",
    docRefs: ["doc/testing/agentic-tests/agentic-feature-surface.md"],
    dependencies: ["nav-connection-status"],
    testability: "ready",
  },
  {
    id: "home-quick-config",
    title: "Home quick config read and verify",
    featureArea: "Home",
    route: "/",
    safetyClass: "read-only",
    primaryOracle: "UI config values plus REST-visible config",
    fallbackOracle: "Diagnostics/log evidence",
    cleanup: "No cleanup required",
    docRefs: [
      "doc/testing/agentic-tests/agentic-action-model.md",
      "doc/testing/agentic-tests/agentic-oracle-catalog.md",
    ],
    dependencies: ["home-readonly-visibility"],
    testability: "ready",
  },
  {
    id: "home-config-snapshot",
    title: "App config snapshot save/load/delete lifecycle",
    featureArea: "Home",
    route: "/",
    safetyClass: "guarded-mutation",
    primaryOracle: "UI plus local persistence",
    fallbackOracle: "Diagnostics/log evidence",
    cleanup: `Delete test-owned snapshots matching prefix '${testNamespaces.configSnapshotPrefix}'`,
    docRefs: [
      "doc/testing/agentic-tests/agentic-action-model.md",
      "doc/testing/agentic-tests/agentic-oracle-catalog.md",
    ],
    dependencies: ["home-readonly-visibility"],
    testability: "ready",
  },
  {
    id: "home-machine-controls",
    title: "Home machine control actions (reset/reboot)",
    featureArea: "Home",
    route: "/",
    safetyClass: "destructive",
    primaryOracle: "UI action confirmation plus REST/state-ref change",
    fallbackOracle: "Diagnostics/log entries for issued action",
    cleanup: "Confirm device returns to known connected state",
    docRefs: [
      "doc/testing/agentic-tests/agentic-safety-policy.md",
      "doc/testing/agentic-tests/agentic-action-model.md",
    ],
    dependencies: ["home-readonly-visibility"],
    testability: "guarded",
  },
  {
    id: "home-ram-workflows",
    title: "RAM save/load/clear workflows",
    featureArea: "Home",
    route: "/",
    safetyClass: "destructive",
    primaryOracle: "Filesystem plus REST/state-ref",
    fallbackOracle: "Diagnostics/log evidence",
    cleanup: `Remove test-owned RAM dumps at '${testNamespaces.ramDumpPrefix}*'`,
    docRefs: [
      "doc/testing/agentic-tests/agentic-action-model.md",
      "doc/testing/agentic-tests/agentic-open-questions.md",
    ],
    dependencies: ["home-readonly-visibility"],
    testability: "partial",
    blockerRef: "AOQ-002",
  },
  {
    id: "home-drives-printer-stream",
    title: "Home inline drive, printer, and stream controls",
    featureArea: "Home",
    route: "/",
    safetyClass: "guarded-mutation",
    primaryOracle: "UI plus REST/FTP-visible state plus diagnostics",
    fallbackOracle: "Diagnostics/log evidence",
    cleanup: "Restore prior drive/stream state",
    docRefs: [
      "doc/testing/agentic-tests/agentic-action-model.md",
      "doc/testing/agentic-tests/agentic-open-questions.md",
    ],
    dependencies: ["home-readonly-visibility"],
    testability: "partial",
    blockerRef: "AOQ-003",
  },

  // --- Play (Mixed readiness) ---
  {
    id: "play-source-browse",
    title: "Play source browsing across Local, C64U, and HVSC",
    featureArea: "Play",
    route: "/play",
    safetyClass: "read-only",
    primaryOracle: "UI source listing plus REST/FTP/filesystem evidence",
    fallbackOracle: "Diagnostics/log evidence",
    cleanup: "No cleanup required",
    docRefs: [
      "doc/testing/agentic-tests/agentic-feature-surface.md",
      "doc/testing/agentic-tests/agentic-action-model.md",
    ],
    dependencies: ["nav-route-shell"],
    testability: "ready",
  },
  {
    id: "play-playlist-build",
    title: "Playlist construction and editing",
    featureArea: "Play",
    route: "/play",
    safetyClass: "guarded-mutation",
    primaryOracle: "UI playlist state plus durable state evidence",
    fallbackOracle: "Diagnostics/log evidence",
    cleanup: "Clear test-built playlist",
    docRefs: [
      "doc/testing/agentic-tests/agentic-action-model.md",
      "doc/testing/agentic-tests/agentic-oracle-catalog.md",
    ],
    dependencies: ["play-source-browse"],
    testability: "ready",
  },
  {
    id: "play-transport-playback",
    title: "Mixed-format playback transport on real hardware",
    featureArea: "Play",
    route: "/play",
    safetyClass: "guarded-mutation",
    primaryOracle: "Play UI transport state plus c64scope A/V assertions",
    fallbackOracle: "Playlist state plus diagnostics/log evidence",
    cleanup: "Stop playback, stop capture, restore stable route state",
    docRefs: [
      "doc/testing/agentic-tests/c64scope-spec.md",
      "doc/testing/agentic-tests/agentic-android-runtime-contract.md",
    ],
    dependencies: ["play-playlist-build"],
    testability: "ready",
  },
  {
    id: "play-duration-volume",
    title: "Playback duration, subsong, and volume control",
    featureArea: "Play",
    route: "/play",
    safetyClass: "guarded-mutation",
    primaryOracle: "UI state plus REST-visible mixer state",
    fallbackOracle: "Diagnostics/log evidence",
    cleanup: "Restore default volume",
    docRefs: [
      "doc/testing/agentic-tests/agentic-oracle-catalog.md",
      "doc/testing/agentic-tests/agentic-action-model.md",
    ],
    dependencies: ["play-transport-playback"],
    testability: "ready",
  },
  {
    id: "play-background-execution",
    title: "Android background playback and lock behavior",
    featureArea: "Play",
    route: "/play",
    safetyClass: "guarded-mutation",
    primaryOracle: "Play state plus Android background-execution logs",
    fallbackOracle: "backgroundAutoSkipDue event plus updated current-item state",
    cleanup: "Stop background execution, return to foreground",
    docRefs: [
      "doc/testing/agentic-tests/agentic-android-runtime-contract.md",
      "doc/testing/agentic-tests/agentic-oracle-catalog.md",
    ],
    dependencies: ["play-transport-playback"],
    testability: "ready",
  },
  {
    id: "play-hvsc-lifecycle",
    title: "HVSC download, install, ingest, browse, and play",
    featureArea: "Play",
    route: "/play",
    safetyClass: "guarded-mutation",
    primaryOracle: "UI status plus progress plus filesystem/ingestion evidence",
    fallbackOracle: "Diagnostics/log evidence with final status",
    cleanup: "Reset HVSC state if isolation required",
    docRefs: [
      "doc/testing/agentic-tests/agentic-action-model.md",
      "doc/testing/agentic-tests/agentic-open-questions.md",
    ],
    dependencies: ["play-source-browse"],
    testability: "guarded",
    blockerRef: "AOQ-007",
  },

  // --- Disks (Guarded/Destructive) ---
  {
    id: "disks-library-browse",
    title: "Disk library browsing and search",
    featureArea: "Disks",
    route: "/disks",
    safetyClass: "read-only",
    primaryOracle: "UI library listing",
    fallbackOracle: "REST/FTP-visible storage state",
    cleanup: "No cleanup required",
    docRefs: [
      "doc/testing/agentic-tests/agentic-feature-surface.md",
      "doc/testing/agentic-tests/agentic-action-model.md",
    ],
    dependencies: ["nav-route-shell"],
    testability: "ready",
  },
  {
    id: "disks-mount-eject",
    title: "Disk mount/eject to Drive A and Drive B",
    featureArea: "Disks",
    route: "/disks",
    safetyClass: "guarded-mutation",
    primaryOracle: "UI plus REST-visible drive/mount state",
    fallbackOracle: "FTP-visible file presence and drive-status text",
    cleanup: "Eject test-mounted disks",
    docRefs: [
      "doc/testing/agentic-tests/agentic-action-model.md",
      "doc/testing/agentic-tests/agentic-oracle-catalog.md",
    ],
    dependencies: ["disks-library-browse"],
    testability: "guarded",
  },
  {
    id: "disks-drive-config",
    title: "Drive power, reset, bus ID, and drive type controls",
    featureArea: "Disks",
    route: "/disks",
    safetyClass: "guarded-mutation",
    primaryOracle: "UI plus REST-visible drive state",
    fallbackOracle: "Diagnostics/log evidence",
    cleanup: "Restore baseline drive configuration",
    docRefs: [
      "doc/testing/agentic-tests/agentic-action-model.md",
      "doc/testing/agentic-tests/agentic-safety-policy.md",
    ],
    dependencies: ["disks-library-browse"],
    testability: "guarded",
  },
  {
    id: "disks-library-management",
    title: "Disk library import, rename, delete with test-owned fixtures",
    featureArea: "Disks",
    route: "/disks",
    safetyClass: "destructive",
    primaryOracle: "UI library diff plus mounted-state confirmation",
    fallbackOracle: "FTP-visible storage state",
    cleanup: `Delete only entries matching prefix '${testNamespaces.diskLibraryPrefix}'`,
    docRefs: [
      "doc/testing/agentic-tests/agentic-safety-policy.md",
      "doc/testing/agentic-tests/agentic-action-model.md",
    ],
    dependencies: ["disks-library-browse"],
    testability: "guarded",
  },

  // --- Config (Partial) ---
  {
    id: "config-browse-readonly",
    title: "Config category discovery and read-only browsing",
    featureArea: "Config",
    route: "/config",
    safetyClass: "read-only",
    primaryOracle: "UI category and item listing",
    fallbackOracle: "REST-visible config tree",
    cleanup: "No cleanup required",
    docRefs: [
      "doc/testing/agentic-tests/agentic-feature-surface.md",
      "doc/testing/agentic-tests/agentic-action-model.md",
    ],
    dependencies: ["nav-route-shell"],
    testability: "ready",
  },
  {
    id: "config-edit-roundtrip",
    title: "Config item edit and value round-trip",
    featureArea: "Config",
    route: "/config",
    safetyClass: "guarded-mutation",
    primaryOracle: "UI value round-trip plus REST-visible config state",
    fallbackOracle: "Diagnostics/log confirmation",
    cleanup: "Restore original config value",
    docRefs: [
      "doc/testing/agentic-tests/agentic-action-model.md",
      "doc/testing/agentic-tests/agentic-open-questions.md",
    ],
    dependencies: ["config-browse-readonly"],
    testability: "partial",
    blockerRef: "AOQ-004",
  },
  {
    id: "config-audio-mixer",
    title: "Audio Mixer solo/reset flows",
    featureArea: "Config",
    route: "/config",
    safetyClass: "guarded-mutation",
    primaryOracle: "UI plus REST-visible config plus logs",
    fallbackOracle: "Diagnostics/log confirmation for resets",
    cleanup: "Reset mixer to defaults",
    docRefs: [
      "doc/testing/agentic-tests/agentic-action-model.md",
      "doc/testing/agentic-tests/agentic-open-questions.md",
    ],
    dependencies: ["config-browse-readonly"],
    testability: "partial",
    blockerRef: "AOQ-005",
  },

  // --- Settings (Ready/Partial mix) ---
  {
    id: "settings-connection-theme",
    title: "Settings connection host, theme, and app preferences",
    featureArea: "Settings",
    route: "/settings",
    safetyClass: "guarded-mutation",
    primaryOracle: "UI state plus persistence plus logs",
    fallbackOracle: "Diagnostics/log evidence",
    cleanup: "Restore original settings values",
    docRefs: [
      "doc/testing/agentic-tests/agentic-action-model.md",
      "doc/testing/agentic-tests/agentic-oracle-catalog.md",
    ],
    dependencies: ["nav-route-shell"],
    testability: "ready",
  },
  {
    id: "settings-diagnostics",
    title: "Diagnostics dialog tabs, clear, and export",
    featureArea: "Settings",
    route: "/settings",
    safetyClass: "guarded-mutation",
    primaryOracle: "UI plus filesystem/diagnostics-ZIP evidence",
    fallbackOracle: "Diagnostics/log and trace evidence",
    cleanup: "No cleanup required for read; restore after clear",
    docRefs: [
      "doc/testing/agentic-tests/agentic-observability-model.md",
      "doc/testing/agentic-tests/agentic-open-questions.md",
    ],
    dependencies: ["settings-connection-theme"],
    testability: "partial",
    blockerRef: "AOQ-006",
  },
  {
    id: "settings-import-export",
    title: "Settings export and import lifecycle",
    featureArea: "Settings",
    route: "/settings",
    safetyClass: "guarded-mutation",
    primaryOracle: "UI state plus exported file evidence",
    fallbackOracle: "Diagnostics bundle contents",
    cleanup: `Remove test-owned exports matching prefix '${testNamespaces.settingsExportPrefix}'`,
    docRefs: [
      "doc/testing/agentic-tests/agentic-oracle-catalog.md",
      "doc/testing/agentic-tests/agentic-open-questions.md",
    ],
    dependencies: ["settings-connection-theme"],
    testability: "partial",
    blockerRef: "AOQ-006",
  },
  {
    id: "settings-device-safety",
    title: "Device Safety preset and advanced controls",
    featureArea: "Settings",
    route: "/settings",
    safetyClass: "destructive",
    primaryOracle: "UI plus persisted config",
    fallbackOracle: "Diagnostics/log evidence",
    cleanup: "Restore baseline safety preset",
    docRefs: [
      "doc/testing/agentic-tests/agentic-safety-policy.md",
      "doc/testing/agentic-tests/agentic-open-questions.md",
    ],
    dependencies: ["settings-connection-theme"],
    testability: "partial",
    blockerRef: "AOQ-009",
  },

  // --- Docs and Licenses (Ready, Read-only) ---
  {
    id: "docs-help-content",
    title: "Docs page accordion sections and help content",
    featureArea: "Docs",
    route: "/docs",
    safetyClass: "read-only",
    primaryOracle: "UI content rendering",
    fallbackOracle: "Error-log absence",
    cleanup: "No cleanup required",
    docRefs: [
      "doc/testing/agentic-tests/agentic-feature-surface.md",
      "doc/testing/agentic-tests/agentic-action-model.md",
    ],
    dependencies: ["nav-route-shell"],
    testability: "ready",
  },
  {
    id: "docs-licenses",
    title: "Open-source licenses page rendering",
    featureArea: "Docs",
    route: "/settings/open-source-licenses",
    safetyClass: "read-only",
    primaryOracle: "UI content rendering",
    fallbackOracle: "Error-log absence",
    cleanup: "No cleanup required",
    docRefs: [
      "doc/testing/agentic-tests/agentic-feature-surface.md",
      "doc/testing/agentic-tests/agentic-action-model.md",
    ],
    dependencies: ["nav-route-shell"],
    testability: "ready",
  },
];
