#!/usr/bin/env python3
"""What a DEEP SID Radio station costs on the Pixel 4 (spec §9.2 / §12.6).

``sid_radio_hil.py`` soaks a station for tens of tracks. That is the right test for continuity and
determinism, and the wrong test for cost: every per-refill expense that scales with the exclusion set
is invisible at 45 tracks, and the depth where it bites — tens of thousands of exclusions — is weeks
of listening away. A clean shallow run therefore proves nothing about deep behaviour, so reporting
one as a pass would be misleading.

This harness puts the app into a deep session directly, by writing the persisted session descriptor a
real station reaches after serving N tracks (generated by
``scripts/sidRadio/measure-station-depth.ts --emit-sessions``) and letting the app resume from it.
That is not a synthetic state: it is exactly what a resumed deep session is, and the resume path
already has to serve it correctly.

At each depth it reports:

  * the pinned §9.2/§12.6 budgets, via the same ``assert_budgets`` the shallow runner uses;
  * the cost of the three operations that scale with the exclusion set, timed **in the page on the
    device** rather than extrapolated from a desktop — the per-refill session write
    (``JSON.stringify``), the per-compute worker post (``structuredClone``), and the engine's
    ``new Set(exclude)``;
  * per-thread CPU in the WebView renderer process, which is where both the station's main-thread
    work and the WASM SID render live, so the station's share can be separated from the render's.

Usage:
  python3 tools/hil/sid_radio_depth_hil.py --serial <ADB_SERIAL> \
      --sessions tmp/deep-sessions --depths 1000,10000,30000,60000
"""
from __future__ import annotations

import argparse
import json
import subprocess
import time
from pathlib import Path

import sid_radio_hil as hil

RENDERER_PROCESS_HINT = "SandboxedProcessService"
CHUNK_CHARS = 96 * 1024


def renderer_pid(serial: str) -> int | None:
    """The WebView renderer process — the JS main thread, the station worker and the SID render."""
    out = hil.adb(serial, "shell", "ps", "-A", "-o", "PID,NAME")
    for line in out.splitlines():
        if RENDERER_PROCESS_HINT in line:
            return int(line.split()[0])
    return None


def thread_cpu(serial: str, pid: int, seconds: float) -> list[tuple[str, float]]:
    """Per-thread CPU as a share of one core over `seconds`.

    A cumulative counter says which thread has worked hardest since launch; the question here is
    whether anything is competing with the audio render *now*, so this is a rate.
    """

    def snap() -> dict[int, tuple[str, int]]:
        raw = hil.adb(serial, "shell", f"cat /proc/{pid}/task/*/stat 2>/dev/null")
        out: dict[int, tuple[str, int]] = {}
        for line in raw.splitlines():
            # comm can contain spaces; it is parenthesised, so split around it.
            if "(" not in line or ")" not in line:
                continue
            tid = int(line[: line.index("(")].strip())
            name = line[line.index("(") + 1 : line.rindex(")")]
            fields = line[line.rindex(")") + 2 :].split()
            # utime and stime are fields 14 and 15 of stat, i.e. 12 and 13 after comm+state.
            # Keyed by tid, not name: Chrome gives every dedicated worker the same comm, so a
            # name-keyed map silently reports one worker and drops the other — which for this
            # question is the difference between the SID render and the station engine.
            out[tid] = (name, int(fields[11]) + int(fields[12]))
        return out

    before = snap()
    time.sleep(seconds)
    after = snap()
    rates = []
    for tid, (name, end) in after.items():
        previous = before.get(tid)
        if previous is None:
            continue
        jiffies = end - previous[1]
        if jiffies <= 0:
            continue
        rates.append((f"{name}#{tid}", 100.0 * (jiffies / 100.0) / seconds))
    rates.sort(key=lambda item: -item[1])
    return rates


def write_session(cdp: hil.Cdp, descriptor_json: str) -> None:
    """Install a persisted station descriptor, chunked — 495 KB does not fit one CDP evaluate."""
    cdp.evaluate("window.__deep = ''; 'ok'")
    for start in range(0, len(descriptor_json), CHUNK_CHARS):
        chunk = json.dumps(descriptor_json[start : start + CHUNK_CHARS])
        cdp.evaluate(f"window.__deep += {chunk}; 'ok'")
    stored = cdp.evaluate(
        "(() => { localStorage.setItem('c64u_sid_radio_session', window.__deep);"
        " return localStorage.getItem('c64u_sid_radio_session').length; })()"
    )
    if stored != len(descriptor_json):
        raise SystemExit(f"sid_radio_depth_hil: stored {stored} chars, expected {len(descriptor_json)}")


SCALING_COST_JS = """
(() => {
  const raw = localStorage.getItem('c64u_sid_radio_session');
  if (!raw) return null;
  const descriptor = JSON.parse(raw);
  const exclude = descriptor.excludeOrdinals;
  const time = (runs, fn) => {
    fn();
    const started = performance.now();
    for (let i = 0; i < runs; i += 1) fn();
    return (performance.now() - started) / runs;
  };
  let sink = 0;
  return {
    exclusions: exclude.length,
    jsonBytes: raw.length,
    stringifyMs: time(5, () => { sink += JSON.stringify(descriptor).length; }),
    structuredCloneMs: time(5, () => { sink += structuredClone(exclude).length; }),
    newSetMs: time(5, () => { sink += new Set(exclude).size; }),
    sink,
  };
})()
"""


def scaling_costs(cdp: hil.Cdp) -> dict | None:
    return cdp.evaluate(SCALING_COST_JS)


def wait_for_station(cdp: hil.Cdp, timeout_s: float = 90.0) -> dict | None:
    """Wait until the resumed station has refilled and reports itself active."""
    deadline = time.time() + timeout_s
    while time.time() < deadline:
        stats = hil.read_stats(cdp)
        if stats and stats.get("stationActive") and stats.get("candidatesEmitted", 0) > 0:
            return stats
        time.sleep(2)
    return hil.read_stats(cdp)


def start_mic(path: str, seconds: float, device: str) -> subprocess.Popen | None:
    """Record the phone's speaker while the station is genuinely playing, not across the reloads."""
    if not device:
        return None
    return subprocess.Popen(
        ["arecord", "-D", device, "-f", "S16_LE", "-r", "48000", "-c", "1", "-d", str(int(seconds)), path],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )


def probe_depth(
    cdp: hil.Cdp,
    serial: str,
    descriptor_json: str,
    sample_seconds: float,
    play_seconds: float,
    mic_path: str,
    mic_device: str,
) -> dict:
    hil.stop_active_station(cdp)
    write_session(cdp, descriptor_json)
    cdp.send("Page.reload", {"ignoreCache": False})
    time.sleep(7)
    hil.open_play_tab(cdp)

    resumed = wait_for_station(cdp)
    playing = hil.ensure_playing(cdp, timeout_s=60)

    # Only now is audio genuinely running, so this is the window worth recording: a mic file that
    # spanned the reload would show a silence the app is not responsible for.
    mic = start_mic(mic_path, play_seconds + sample_seconds + 2, mic_device)
    # Let the queue drain into real lookahead refills, which is where the per-refill cost is paid.
    time.sleep(play_seconds)

    pid = renderer_pid(serial)
    cpu = thread_cpu(serial, pid, sample_seconds) if pid else []
    stats = hil.read_stats(cdp) or {}
    scaling = scaling_costs(cdp)
    if mic:
        mic.wait(timeout=play_seconds + sample_seconds + 30)
    return {
        "resumed": bool(resumed and resumed.get("stationActive")),
        "playing": playing,
        "stats": stats,
        "scaling": scaling,
        "rendererPid": pid,
        "threadCpu": cpu,
        "mic": mic_path if mic else None,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="SID Radio cost at depth, Pixel 4")
    parser.add_argument("--serial", required=True)
    parser.add_argument("--sessions", default="tmp/deep-sessions")
    parser.add_argument("--depths", default="1000,10000,30000,60000")
    parser.add_argument("--engine", choices=["c64", "local"], default="local")
    parser.add_argument("--play-seconds", type=float, default=90.0)
    parser.add_argument("--sample-seconds", type=float, default=20.0)
    parser.add_argument("--mic-device", default="plughw:CARD=SF558,DEV=0")
    parser.add_argument("--mic-dir", default="")
    parser.add_argument("--out", default="")
    args = parser.parse_args()

    hil.forward_devtools(args.serial)
    cdp = hil.Cdp()
    results: list[dict] = []
    try:
        hil.enable_flags(cdp, engine=args.engine)
        for depth in [int(d) for d in args.depths.split(",")]:
            path = Path(args.sessions) / f"session-{depth}.json"
            descriptor = path.read_text()
            print(f"\n[depth-hil] === depth {depth}: {len(descriptor)} chars of descriptor ===", flush=True)
            mic_path = str(Path(args.mic_dir) / f"depth-{depth}.wav") if args.mic_dir else ""
            result = probe_depth(
                cdp,
                args.serial,
                descriptor,
                args.sample_seconds,
                args.play_seconds,
                mic_path,
                args.mic_device if args.mic_dir else "",
            )
            result["depth"] = depth
            results.append(result)

            scaling = result["scaling"] or {}
            print(
                f"[depth-hil] depth {depth}: resumed={result['resumed']} playing={result['playing']}"
                f" exclusions={scaling.get('exclusions')} sessionBytes={scaling.get('jsonBytes')}",
                flush=True,
            )
            if scaling:
                stringify = scaling["stringifyMs"]
                clone = scaling["structuredCloneMs"]
                new_set = scaling["newSetMs"]
                print(
                    f"[depth-hil] depth {depth}: ON-DEVICE stringify={stringify:.2f} ms"
                    f"  structuredClone={clone:.2f} ms  newSet={new_set:.2f} ms"
                    f"  mainThreadPerRefill={stringify + clone:.2f} ms",
                    flush=True,
                )
            else:
                print(f"[depth-hil] depth {depth}: no scaling costs read", flush=True)
            for name, rate in result["threadCpu"][:6]:
                print(f"[depth-hil] depth {depth}: cpu {name:<24} {rate:5.1f}% of a core", flush=True)
            hil.assert_budgets(result["stats"], ("thresholds", "localEngine"))
    finally:
        cdp.close()
        if args.out:
            Path(args.out).write_text(json.dumps(results, indent=2))
            print(f"[depth-hil] wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
