/*
 * C64 Commander - Configure and control your Commodore 64 Ultimate over your local network
 * Copyright (C) 2026 Christian Gleissner
 *
 * Licensed under the GNU General Public License v3.0 or later.
 * See <https://www.gnu.org/licenses/> for details.
 */

import { test, expect } from "@playwright/test";
import { spawnSync } from "node:child_process";
import * as fs from "node:fs";
import * as path from "node:path";
import type { Page, TestInfo } from "@playwright/test";
import { createMockC64Server } from "../tests/mocks/mockC64Server";
import { seedUiMocks, uiFixtures } from "./uiMocks";
import { seedFtpConfig, startFtpTestServers } from "./ftpTestUtils";
import { assertNoUiIssues, attachStepScreenshot, finalizeEvidence, startStrictUiMonitoring } from "./testArtifacts";
import { enableTraceAssertions } from "./traceUtils";
import { saveCoverageFromPage } from "./withCoverage";
import { clickSourceSelectionButton } from "./sourceSelection";

const runGit = (args: string[]) => {
  const result = spawnSync("git", args, { encoding: "utf-8" });
  return result.status === 0 ? result.stdout.trim() : "";
};

// Resolve the expected version using the same priority order as vite.config.ts:
//   1. CI-injected explicit version (VITE_APP_VERSION, VERSION_NAME, tag context)
//   2. src/version.ts written by scripts/resolve-version.sh via prebuild
//   3. Replicate the script's git logic directly as final fallback
//
// Version format: <tag>  OR  <tag>-<5-char-lowercase-hex-SHA>
// Any other format is a test failure against the invariant.
const resolveExpectedVersion = () => {
  // Priority 1: CI explicit version injection
  const envVersion = process.env.VITE_APP_VERSION || process.env.VERSION_NAME || "";
  if (envVersion) return envVersion;

  if (process.env.GITHUB_REF_TYPE === "tag" && process.env.GITHUB_REF_NAME) {
    return process.env.GITHUB_REF_NAME;
  }

  const tagFromRef = (() => {
    const ref = process.env.GITHUB_REF?.trim() ?? "";
    return ref.startsWith("refs/tags/") ? ref.slice("refs/tags/".length) : "";
  })();
  if (tagFromRef) return tagFromRef;

  // Priority 2: read from src/version.ts generated by scripts/resolve-version.sh
  try {
    const content = fs.readFileSync(path.resolve("src/version.ts"), "utf-8");
    const m = content.match(/APP_VERSION\s*=\s*'([^']*)'/);
    if (m?.[1]) return m[1];
  } catch {
    // fall through to git logic below
  }

  // Priority 3: replicate resolve-version.sh logic directly
  const tag = runGit(["describe", "--tags", "--abbrev=0"]);
  if (!tag) return "";
  const sha5 = runGit(["rev-parse", "--short=5", "HEAD"]);
  const diffResult = spawnSync("git", ["diff", "--quiet", "HEAD", "--"], { encoding: "utf-8" });
  const isDirty = diffResult.status !== 0;
  return isDirty && sha5 ? `${tag}-${sha5}` : tag;
};

test.describe("UI coverage", () => {
  test.describe.configure({ mode: "parallel" });
  const servers = new Map<string, Awaited<ReturnType<typeof createMockC64Server>>>();

  test.beforeEach(async ({ page }: { page: Page }, testInfo: TestInfo) => {
    enableTraceAssertions(testInfo);
    await startStrictUiMonitoring(page, testInfo);
    const server = await createMockC64Server(uiFixtures.configState);
    servers.set(testInfo.testId, server);
    await seedUiMocks(page, server.baseUrl);
    await page.addStyleTag({
      content: '[aria-label="Notifications (F8)"] { pointer-events: none !important; }',
    });
  });

  test.afterEach(async ({ page }: { page: Page }, testInfo: TestInfo) => {
    const server = servers.get(testInfo.testId);
    try {
      await saveCoverageFromPage(page, testInfo.title);
      await assertNoUiIssues(page, testInfo);
    } finally {
      await finalizeEvidence(page, testInfo);
      if (server) {
        await server.close();
        servers.delete(testInfo.testId);
      }
    }
  });

  const clickAllButtons = async (
    page: Page,
    scope: Page | ReturnType<Page["locator"]>,
    options: { maxClicks?: number; timeBudgetMs?: number } = {},
  ) => {
    const locator = "locator" in scope ? scope.locator("button") : scope.locator("button");
    const handles = await locator.elementHandles();
    const maxClicks = options.maxClicks ?? 12;
    const deadline = Date.now() + (options.timeBudgetMs ?? 1500);
    let clicks = 0;
    for (const handle of handles) {
      if (page.isClosed()) return;
      if (clicks >= maxClicks || Date.now() > deadline) return;
      const isClickable = await handle.evaluate((el: Element) => {
        const button = el as HTMLButtonElement;
        const ariaDisabled = button.getAttribute("aria-disabled") === "true";
        const skipClick = button.hasAttribute("data-skip-click");
        return !skipClick && !button.disabled && !ariaDisabled && button.offsetParent !== null;
      });
      if (!isClickable) continue;
      try {
        await handle.scrollIntoViewIfNeeded();
        await handle.click();
        clicks += 1;
      } catch (error) {
        console.warn("Button click failed during UI sweep", error);
      }

      const closeButton = page.getByRole("button", { name: /close|cancel|done|dismiss|back/i }).first();
      try {
        if (!page.isClosed() && (await closeButton.isVisible())) {
          await closeButton.click();
        }
      } catch (error) {
        console.warn("Close action failed during UI sweep", error);
      }
    }
  };

  const enableDeveloperMode = async (page: Page) => {
    await page.goto("/settings");
    const aboutButton = page.getByRole("button", { name: "About" });
    for (let i = 0; i < 7; i += 1) {
      await aboutButton.click();
    }
  };

  const enableHvscDownloads = async (page: Page) => {
    await enableDeveloperMode(page);
    const toggle = page.getByLabel("Enable HVSC downloads");
    await expect(toggle).toBeVisible();
    if (!(await toggle.isChecked())) {
      await toggle.click();
    }
    await expect(toggle).toBeChecked();
  };

  const ensureRemoteRoot = async (page: Page) => {
    const rootButton = page.locator('[data-testid="navigate-root"]');
    const visible = await rootButton.isVisible().catch(() => false);
    if (!visible) return;
    const disabledAttr = await rootButton.getAttribute("disabled").catch(() => null);
    const ariaDisabled = await rootButton.getAttribute("aria-disabled").catch(() => null);
    if (disabledAttr !== null || ariaDisabled === "true") return;
    try {
      await rootButton.click({ timeout: 2000 });
    } catch {
      // Ignore: navigation may have already reached root.
    }
  };

  const snap = async (page: Page, testInfo: TestInfo, label: string) => {
    await attachStepScreenshot(page, testInfo, label);
  };

  test("config widgets read/write and refresh", async ({ page }: { page: Page }, testInfo: TestInfo) => {
    const server = servers.get(testInfo.testId);
    if (!server) {
      throw new Error("Missing mock C64 server for UI coverage test.");
    }
    await page.goto("/config", { waitUntil: "domcontentloaded" });
    await snap(page, testInfo, "config-open");
    await expect(page.getByRole("button", { name: "U64 Specific Settings" })).toBeVisible();
    await page.getByRole("button", { name: "U64 Specific Settings" }).click();

    const selectTrigger = page.getByLabel("System Mode select");
    await selectTrigger.click();
    await page.getByRole("option", { name: /^NTSC$/ }).click();

    await page.goto("/config", { waitUntil: "domcontentloaded" });
    const audioMixerButton = page.getByTestId("config-category-audio-mixer");
    await expect(audioMixerButton).toBeVisible();
    await audioMixerButton.click();
    await snap(page, testInfo, "audio-mixer-open");
    const slider = page.getByLabel("Vol UltiSid 1 slider");
    const sliderBox = await slider.boundingBox();
    if (sliderBox) {
      await slider.click({
        position: { x: sliderBox.width - 2, y: sliderBox.height / 2 },
      });
    }

    await expect.poll(() => server.getState()["U64 Specific Settings"]["System Mode"].value).toBe("NTSC");
    await expect.poll(() => server.getState()["Audio Mixer"]["Vol UltiSid 1"].value).toBe("+6 dB");

    const refreshCount = server.requests.length;
    const refreshButton = page.getByRole("button", { name: "Refresh" }).first();
    await refreshButton.click();
    await expect.poll(() => server.requests.length).toBeGreaterThan(refreshCount);
    await snap(page, testInfo, "config-refreshed");

    const systemModeSelect = page.getByLabel("System Mode select");
    if ((await systemModeSelect.count()) === 0) {
      await page.getByRole("button", { name: "U64 Specific Settings" }).click();
    }
    await expect(systemModeSelect).toBeVisible();
    await expect(systemModeSelect).toContainText("NTSC");
    await snap(page, testInfo, "config-updated");
  });

  test("config group actions stay at top of expanded section", async ({ page }: { page: Page }, testInfo: TestInfo) => {
    await page.goto("/config", { waitUntil: "domcontentloaded" });
    await snap(page, testInfo, "config-open");
    await page.getByRole("button", { name: "Audio Mixer" }).click();
    await snap(page, testInfo, "audio-mixer-expanded");
    const actions = page.getByTestId("config-group-actions");
    const list = page.getByTestId("config-group-list");
    const [actionsBox, listBox] = await Promise.all([actions.boundingBox(), list.boundingBox()]);
    expect(actionsBox?.y ?? 0).toBeLessThan(listBox?.y ?? Number.MAX_SAFE_INTEGER);
  });

  test("home and disks pages render", async ({ page }: { page: Page }, testInfo: TestInfo) => {
    await page.goto("/", { waitUntil: "domcontentloaded" });
    await expect(page.getByRole("heading", { name: "HOME" })).toBeVisible();
    await snap(page, testInfo, "home-open");

    await page.goto("/disks", { waitUntil: "domcontentloaded" });
    await expect(page.locator("header").getByRole("heading", { name: "Disks" })).toBeVisible();
    await snap(page, testInfo, "disks-open");
  });

  test("source indicator icons invert in dark mode", async ({ page }: { page: Page }, testInfo: TestInfo) => {
    await page.addInitScript(() => {
      localStorage.setItem("c64u_theme", "system");
      const playlist = {
        items: [{ source: "local", path: "/demo.sid", name: "demo.sid" }],
        currentIndex: -1,
      };
      localStorage.setItem("c64u_last_device_id", "TEST-123");
      localStorage.setItem("c64u_playlist:v1:TEST-123", JSON.stringify(playlist));
      localStorage.setItem("c64u_playlist:v1:default", JSON.stringify(playlist));
      localStorage.setItem(
        "c64u_disk_library:TEST-123",
        JSON.stringify({
          disks: [
            {
              id: "local:/Disks/demo.d64",
              name: "demo.d64",
              path: "/Disks/demo.d64",
              location: "local",
              group: null,
              importedAt: new Date().toISOString(),
            },
          ],
        }),
      );
    });

    await page.emulateMedia({ colorScheme: "light" });
    await page.goto("/play", { waitUntil: "domcontentloaded" });
    const playIcon = page.getByTestId("file-origin-icon").first();
    await expect(playIcon).toBeVisible();
    const lightFilter = await playIcon.evaluate((el) => getComputedStyle(el).filter);
    await snap(page, testInfo, "play-icons-light");

    await page.emulateMedia({ colorScheme: "dark" });
    await expect.poll(async () => playIcon.evaluate((el) => getComputedStyle(el).filter)).not.toBe(lightFilter);
    const darkFilter = await playIcon.evaluate((el) => getComputedStyle(el).filter);
    expect(darkFilter).not.toBe("none");
    await snap(page, testInfo, "play-icons-dark");

    await page.goto("/disks", { waitUntil: "domcontentloaded" });
    const diskIcon = page.getByTestId("file-origin-icon").first();
    await expect(diskIcon).toBeVisible();
    const diskFilter = await diskIcon.evaluate((el) => getComputedStyle(el).filter);
    expect(diskFilter).not.toBe("none");
    await snap(page, testInfo, "disk-icons-dark");
  });

  test("home page shows resolved version", async ({ page }: { page: Page }, testInfo: TestInfo) => {
    await page.goto("/", { waitUntil: "domcontentloaded" });
    const expectedVersion = resolveExpectedVersion() || "—";
    const versionText = page.getByTestId("home-system-version");
    if (expectedVersion === "—") {
      await expect(versionText).toHaveText("—");
    } else {
      // Strict invariant: version must be exactly <tag> or <tag>-<5-char-lowercase-hex-SHA>.
      // Any other format (8-char SHA, branch name, build metadata) is a violation.
      await expect(versionText).toHaveText(expectedVersion);
    }
    await snap(page, testInfo, "home-version");
  });

  test("config page renders and toggles a section", async ({ page }: { page: Page }, testInfo: TestInfo) => {
    await page.goto("/config", { waitUntil: "domcontentloaded" });
    await snap(page, testInfo, "config-open");
    const section = page.getByRole("button", { name: "U64 Specific Settings" });
    await section.click();
    await expect(page.getByText("System Mode")).toBeVisible();
    await snap(page, testInfo, "section-expanded");
  });

  test("play page renders with HVSC controls", async ({ page }: { page: Page }, testInfo: TestInfo) => {
    await enableHvscDownloads(page);
    await page.goto("/play", { waitUntil: "domcontentloaded" });
    await expect(page.getByRole("heading", { name: "Play Files" })).toBeVisible();
    await expect(page.getByRole("button", { name: "Download HVSC" })).toBeVisible();
    await snap(page, testInfo, "play-hvsc");
  });

  test("add-items shows progress feedback after confirm", async ({ page }: { page: Page }, testInfo: TestInfo) => {
    const ftpServers = await startFtpTestServers();
    await seedFtpConfig(page, {
      host: ftpServers.ftpServer.host,
      port: ftpServers.ftpServer.port,
      bridgeUrl: ftpServers.bridgeServer.baseUrl,
      password: "",
    });
    await page.route("**/v1/ftp/list", async (route) => {
      await new Promise((resolve) => setTimeout(resolve, 300));
      await route.continue();
    });
    await page.goto("/play");
    await snap(page, testInfo, "play-open");
    await page.getByRole("button", { name: /Add items|Add more items/i }).click();
    const dialog = page.getByRole("dialog");
    await clickSourceSelectionButton(dialog, "C64 Ultimate");
    await ensureRemoteRoot(page);
    await expect(dialog.getByText("Usb0", { exact: true })).toBeVisible();
    await snap(page, testInfo, "c64u-root");
    await dialog.locator('[data-testid="source-entry-row"]', { hasText: "Usb0" }).first().click();
    await dialog.locator('[data-testid="source-entry-row"]', { hasText: "Games" }).first().click();
    await dialog.locator('[data-testid="source-entry-row"]', { hasText: "Turrican II" }).first().click();
    await dialog
      .locator('[data-testid="source-entry-row"]', { hasText: "Disk 1.d64" })
      .first()
      .getByRole("checkbox")
      .click();
    await page.getByTestId("add-items-confirm").click();
    await expect(page.getByTestId("add-items-progress")).toBeVisible();
    await snap(page, testInfo, "progress-visible");
    await expect(page.getByTestId("playlist-list")).toContainText("Disk 1.d64");
    await ftpServers.close();
  });

  test("selection state stays stable when filtering", async ({ page }: { page: Page }, testInfo: TestInfo) => {
    const ftpServers = await startFtpTestServers();
    await seedFtpConfig(page, {
      host: ftpServers.ftpServer.host,
      port: ftpServers.ftpServer.port,
      bridgeUrl: ftpServers.bridgeServer.baseUrl,
      password: "",
    });
    await page.goto("/play");
    await snap(page, testInfo, "play-open");
    await page.getByRole("button", { name: /Add items|Add more items/i }).click();
    const dialog = page.getByRole("dialog");
    await clickSourceSelectionButton(dialog, "C64 Ultimate");
    await ensureRemoteRoot(page);
    await expect(dialog.getByText("Usb0", { exact: true })).toBeVisible();
    await dialog.locator('[data-testid="source-entry-row"]', { hasText: "Usb0" }).first().click();
    await expect(dialog.getByText("Games", { exact: true })).toBeVisible();
    await dialog.locator('[data-testid="source-entry-row"]', { hasText: "Games" }).first().click();
    await expect(dialog.getByText("Turrican II", { exact: true })).toBeVisible();
    await dialog.locator('[data-testid="source-entry-row"]', { hasText: "Turrican II" }).first().click();
    await expect(dialog.getByText("Disk 1.d64", { exact: true })).toBeVisible();
    await dialog
      .locator('[data-testid="source-entry-row"]', { hasText: "Disk 1.d64" })
      .first()
      .getByRole("checkbox")
      .click();
    await snap(page, testInfo, "selection-made");

    await page.getByTestId("add-items-filter").fill("Disk");
    await expect(page.getByTestId("add-items-selection-count")).toHaveText(/1 selected/i);
    await snap(page, testInfo, "filter-applied");
    await ftpServers.close();
  });

  test("item browser does not overflow viewport width", async ({ page }: { page: Page }, testInfo: TestInfo) => {
    const ftpServers = await startFtpTestServers();
    await seedFtpConfig(page, {
      host: ftpServers.ftpServer.host,
      port: ftpServers.ftpServer.port,
      bridgeUrl: ftpServers.bridgeServer.baseUrl,
      password: "",
    });
    await page.goto("/play");
    await snap(page, testInfo, "play-open");
    await page.getByRole("button", { name: /Add items|Add more items/i }).click();
    const dialog = page.getByRole("dialog");
    await clickSourceSelectionButton(dialog, "C64 Ultimate");
    await ensureRemoteRoot(page);
    await dialog.locator('[data-testid="source-entry-row"]', { hasText: "Usb0" }).first().click();
    await dialog.locator('[data-testid="source-entry-row"]', { hasText: "Games" }).first().click();
    await dialog.locator('[data-testid="source-entry-row"]', { hasText: "Turrican II" }).first().click();
    await snap(page, testInfo, "deep-folder");

    const hasOverflow = await page.evaluate(
      () => document.documentElement.scrollWidth > document.documentElement.clientWidth,
    );
    expect(hasOverflow).toBe(false);
    await snap(page, testInfo, "no-overflow");
    await ftpServers.close();
  });

  test("settings and docs pages render", async ({ page }: { page: Page }, testInfo: TestInfo) => {
    await page.goto("/settings", { waitUntil: "domcontentloaded" });
    await expect(page.getByRole("heading", { name: "Settings" })).toBeVisible();
    await snap(page, testInfo, "settings-open");

    await page.goto("/docs", { waitUntil: "domcontentloaded" });
    await expect(page.getByRole("heading", { name: "Docs" })).toBeVisible();
    await snap(page, testInfo, "docs-open");
  });
});
