/*
 * C64 Commander - Configure and control your Commodore 64 Ultimate over your local network
 * Copyright (C) 2026 Christian Gleissner
 *
 * Licensed under the GNU General Public License v3.0 or later.
 * See <https://www.gnu.org/licenses/> for details.
 */

package uk.gleissner.c64commander

import android.util.Log
import java.io.File
import java.security.MessageDigest

/** Where [DemoHvscArchive] reads its committed inputs: APK assets, or the source tree in a test. */
interface DemoHvscAssets {
  /** The names of the entries directly inside [directory]. */
  fun list(directory: String): List<String>

  fun read(path: String): ByteArray
}

/**
 * The HVSC release Demo Mode offers, generated on the device rather than shipped to keep the APK small.
 * Invented tunes in HVSC's folder layout, packed with the app's own `lib7zz.so` so the real extraction
 * path runs; without that binary no release is offered. Each tune's Songlengths.md5 entry starts with
 * a SID Radio corpus identity so stations play it.
 */
class DemoHvscArchive(
        private val cacheDir: File,
        private val sevenZipExecutable: File?,
        private val assets: DemoHvscAssets,
) {
  companion object {
    private const val TAG = "DemoHvscArchive"

    // The name the client scans the index for: HVSC_(\d+)-all-of-them.7z (hvscReleaseService.ts).
    const val RELEASE = 84
    const val ARCHIVE_NAME = "HVSC_$RELEASE-all-of-them.7z"

    const val IDENTITIES_ASSET = "demo-hvsc/identities.txt"

    private val MD5_48 = Regex("^[0-9a-f]{12}$")

    private val COMPOSERS =
            listOf(
                    "Barlow_Kit",
                    "Sidwell_Anna",
                    "Vance_Ruth",
                    "Okonkwo_Ada",
                    "Lindqvist_Nils",
                    "Moreau_Yves",
            )

    private val DEMO_GROUPS = listOf("0-9", "A-F", "G-L", "M-R", "S-Z")

    private val TITLES =
            listOf(
                    "Raster Bar Rag",
                    "Sprite Collision",
                    "Kernal Panic",
                    "Datasette Dreams",
                    "Blue Screen Waltz",
                    "Loading Screen",
                    "Ready Prompt",
                    "Border Flicker",
                    "Sixty Four Kilobytes",
                    "Cassette Rewind",
                    "Floppy Shuffle",
                    "Interrupt Lullaby",
            )
  }

  /** One generated tune: its path inside `C64Music`, as HVSC and the app write it, and its bytes. */
  internal class Tune(val path: String, val bytes: ByteArray)

  internal class Layout(val tunes: List<Tune>, val songlengths: String, val stil: String) {
    /** Changes whenever any generated byte changes, so a device never keeps serving an older build. */
    val fingerprint: String by lazy {
      val digest = MessageDigest.getInstance("SHA-256")
      tunes.forEach { tune ->
        digest.update(tune.path.toByteArray(Charsets.UTF_8))
        digest.update(tune.bytes)
      }
      digest.update(songlengths.toByteArray(Charsets.UTF_8))
      digest.update(stil.toByteArray(Charsets.ISO_8859_1))
      digest.digest().take(8).joinToString("") { "%02x".format(it) }
    }
  }

  private var built: File? = null
  private var generated: Layout? = null

  /** The packed release, or null when this device cannot build one. */
  @Synchronized
  fun archive(): File? {
    built?.let { if (it.isFile) return it }
    val executable = sevenZipExecutable
    if (executable == null || !executable.canExecute()) {
      Log.w(TAG, "No 7-Zip binary available; Demo Mode will offer no HVSC release")
      return null
    }
    return try {
      val packed = build(executable, layout())
      built = packed
      packed
    } catch (error: Exception) {
      Log.w(TAG, "Could not build the demo HVSC release", error)
      null
    }
  }

  @Synchronized
  internal fun layout(): Layout = generated ?: generate().also { generated = it }

  private fun build(executable: File, layout: Layout): File {
    // One directory per fingerprint: a cached archive from an earlier generator would otherwise be
    // served for as long as the app's cache survives, which includes every in-place app update.
    val work = File(cacheDir, "demo-hvsc")
    val release = File(work, layout.fingerprint)
    val target = File(release, ARCHIVE_NAME)
    if (target.isFile && target.length() > 0) return target

    work.deleteRecursively()
    val root = File(release, "C64Music")
    layout.tunes.forEach { tune ->
      File(root, tune.path).apply { parentFile?.mkdirs() }.writeBytes(tune.bytes)
    }
    val documents = File(root, "DOCUMENTS").apply { mkdirs() }
    File(documents, "Songlengths.md5").writeText(layout.songlengths)
    File(documents, "STIL.txt").writeBytes(layout.stil.toByteArray(Charsets.ISO_8859_1))

    // Store rather than compress: these files are tiny and already unique, so the time is all in
    // the container. `-y` because there is no console to answer a prompt.
    val process =
            ProcessBuilder(
                            executable.absolutePath,
                            "a",
                            "-t7z",
                            "-mx0",
                            "-y",
                            target.absolutePath,
                            root.absolutePath,
                    )
                    .directory(release)
                    .redirectErrorStream(true)
                    .start()
    val output = process.inputStream.bufferedReader().use { it.readText() }
    val status = process.waitFor()
    if (status != 0 || !target.isFile) {
      throw IllegalStateException("7-Zip exited $status while packing the demo release: $output")
    }
    Log.i(TAG, "Packed demo HVSC release: ${target.length()} bytes, ${layout.tunes.size} tunes")
    return target
  }

  private fun generate(): Layout {
    val identities = readIdentities()
    val tunes = mutableListOf<Tune>()
    val songlengths = StringBuilder("[Database]\n")

    fun tune(directory: String, title: String, index: Int) {
      val path = "$directory/$title.sid"
      tunes += Tune(path, psid(title, index))

      // Real Songlengths.md5 entries come in pairs: a comment line naming the tune's path, then
      // the MD5 and its durations. Both matter here. The durations are what the app shows, and
      // the PATH line is what puts the tune into the browse index at all — on Android the archive
      // is unpacked natively and the JS side learns which songs exist from this file.
      // mm:ss, with the seconds under sixty: `1:119` was rejected as malformed.
      val seconds = 45 + (index % 200)
      songlengths.append("; ").append(path).append('\n')
      songlengths.append(identities[index].padEnd(32, '0'))
      songlengths.append(String.format("=%d:%02d\n", seconds / 60, seconds % 60))
    }

    // MUSICIANS/<initial>/<Composer>/ — the shape the app's browser navigates.
    val count = identities.size
    var index = 0
    while (tunes.size < count / 2) {
      val composer = COMPOSERS[index % COMPOSERS.size]
      val initial = composer.first().uppercase()
      val title = TITLES[(index / COMPOSERS.size) % TITLES.size]
      val suffix = index / (COMPOSERS.size * TITLES.size)
      val name = if (suffix == 0) title else "$title ${suffix + 1}"
      tune("/MUSICIANS/$initial/$composer", name, index)
      index += 1
    }

    // DEMOS/<range>/ and GAMES/<range>/ — the other two trees a viewer recognises.
    for (tree in listOf("DEMOS", "GAMES")) {
      var group = 0
      while (tunes.size < if (tree == "DEMOS") (count * 3) / 4 else count) {
        val range = DEMO_GROUPS[group % DEMO_GROUPS.size]
        val title = TITLES[index % TITLES.size]
        val suffix = index / TITLES.size
        tune("/$tree/$range", if (suffix == 0) title else "$title ${suffix + 1}", index)
        index += 1
        group += 1
      }
    }
    val stil =
            """
            #  STIL.txt - The SID Tune Information List, demonstration edition
            #
            #  This collection is generated on the device for Demo Mode. The tunes and the
            #  composers are invented; only the directory layout follows the real one.
            #
            /MUSICIANS/B/Barlow_Kit/Raster Bar Rag.sid
               COMMENT: Written for the Demo Mode walkthrough.
            """.trimIndent()
    return Layout(tunes, songlengths.toString(), stil)
  }

  private fun readIdentities(): List<String> {
    val identities =
            String(assets.read(IDENTITIES_ASSET), Charsets.US_ASCII)
                    .lines()
                    .map { it.trim() }
                    .filter { it.isNotEmpty() && !it.startsWith("#") }
    val malformed = identities.filterNot { MD5_48.matches(it) }
    require(identities.isNotEmpty() && malformed.isEmpty()) {
      "$IDENTITIES_ASSET must list md5_48 identities; malformed: ${malformed.take(3)}"
    }
    return identities
  }

  /**
   * A minimal valid PSID v2 file: the 126-byte header the app's parsers read, then a few bytes
   * standing in for the player. Enough to be indexed, named and listed; not music.
   */
  private fun psid(title: String, index: Int): ByteArray {
    val body = ByteArray(126 + 32)
    "PSID".toByteArray(Charsets.US_ASCII).copyInto(body)
    body[4] = 0; body[5] = 2 // version 2
    body[6] = 0; body[7] = 0x7C // data offset 124
    // songs and startSong are 16-bit big-endian: the count belongs in the LOW byte. Writing it
    // into 0x0E declared 256 songs per file, which is what left the tune index unsearchable.
    body[0x0F] = 1 // songs
    body[0x10] = 0; body[0x11] = 1 // start song
    fun text(value: String, at: Int) {
      val bytes = value.take(31).toByteArray(Charsets.ISO_8859_1)
      bytes.copyInto(body, at)
    }
    text(title, 0x16)
    text(COMPOSERS[index % COMPOSERS.size].replace('_', ' '), 0x36)
    text("Demo Mode", 0x56)
    return body
  }
}
