/*
 * C64 Commander - Configure and control your Commodore 64 Ultimate over your local network
 * Copyright (C) 2026 Christian Gleissner
 *
 * Licensed under the GNU General Public License v3.0 or later.
 * See <https://www.gnu.org/licenses/> for details.
 */

import { createRoot } from "react-dom/client";
import App from "./App.tsx";
import { installAsyncContextPropagation } from "./lib/tracing/traceActionContextStore";
import { registerFetchTrace } from "./lib/tracing/fetchTrace";
import { registerUserInteractionCapture } from "./lib/tracing/userInteractionCapture";
import { registerTraceBridge } from "./lib/tracing/traceBridge";
import { registerDiagnosticsTestBridge } from "./lib/diagnostics/diagnosticsTestBridge";
import { registerRemoteInputLatencyBridge } from "./lib/remoteInput/inputLatency";
import { markStartupBootstrapComplete } from "./lib/startup/startupMilestones";
import { initializeRuntimeMotionMode } from "./lib/startup/runtimeMotionBudget";
import { applyStoredTextScale } from "./lib/uiPreferences";
import { registerServiceWorker } from "./lib/startup/serviceWorkerRegistration";
import { silenceLeftoverNativeAudio } from "./lib/streams/silenceLeftoverNativeAudio";
import { stopLeftoverDeviceStreams } from "./lib/streams/leftoverDeviceStreams";
import { addErrorLog } from "./lib/logging";
import { applyFullScreenFromSettings } from "./lib/native/fullScreen";
import { applyScreenOrientationFromSettings } from "./lib/native/screenOrientation";
import { registerSidRadioProbe } from "./lib/sidRadio/sidRadioProbe";
import "./index.css";
// Generated by scripts/compile-styles.mjs. A separate Vite import, not a same-file @import:
// index.css has no postcss-import plugin, and a plain CSS @import is dropped unless it is the
// first rule. Each html[data-app-style="x"] selector outranks the base :root/.dark blocks by
// specificity anyway, so it wins without depending on import order.
import "./generated/appStyles.css";

export const scheduleAfterFirstPaint = (work: () => void) => {
  if (import.meta.env.VITE_ENABLE_TEST_PROBES === "1") {
    work();
    return;
  }
  if (typeof window === "undefined") {
    work();
    return;
  }
  const runWhenIdle = () => {
    const win = window as Window & {
      requestIdleCallback?: (callback: () => void, options?: { timeout: number }) => number;
    };
    if (typeof win.requestIdleCallback === "function") {
      win.requestIdleCallback(() => work(), { timeout: 1200 });
      return;
    }
    window.setTimeout(work, 0);
  };
  // requestAnimationFrame never fires while the document is hidden (spec-mandated
  // throttling), so an app launched in the background (intent, restored session,
  // screen off) would never reach runWhenIdle() at all - skip the rAF gate and go
  // straight to it when already hidden at launch. The normal visible-launch timing
  // (double rAF) is unchanged.
  if (typeof document !== "undefined" && document.hidden) {
    runWhenIdle();
    return;
  }
  window.requestAnimationFrame(() => {
    window.requestAnimationFrame(() => {
      runWhenIdle();
    });
  });
};

const startDeferredStartupBootstrap = () => {
  // Async context propagation must be installed before trace hooks.
  installAsyncContextPropagation();
  registerTraceBridge();
  registerDiagnosticsTestBridge();
  registerRemoteInputLatencyBridge();
  registerFetchTrace();
  registerUserInteractionCapture();
  // SID Radio M0.5 device harness: installs window.__sidRadioProbe only when the
  // flag is on (no-op otherwise); also keeps the worker in the build graph.
  registerSidRadioProbe();
  markStartupBootstrapComplete();
  void import("./lib/startup/secureStorageBootstrap")
    .then(({ primeSecureStorageAfterStartup }) => primeSecureStorageAfterStartup())
    // Only the app's own sockets have been closed so far. If the process died with Live View on,
    // the Ultimate was never told to stop and is still multicasting. Sequenced after the secure
    // storage prime because the stop has to be authenticated on a password-protected device.
    .then(() => stopLeftoverDeviceStreams())
    .catch((error) => {
      const err = error as Error;
      addErrorLog("Deferred secure storage bootstrap failed", {
        error: {
          name: err.name,
          message: err.message,
          stack: err.stack,
        },
      });
    });
};

initializeRuntimeMotionMode();
// Before the first paint, so text is the size the user asked for from the outset
// rather than reflowing once the app has rendered at the default.
applyStoredTextScale();
// The mirror's audio is a NATIVE AudioTrack, so it outlives this WebView. A
// reload leaves it playing while the fresh JavaScript believes nothing is —
// and the next local tune then starts underneath it.
void silenceLeftoverNativeAudio();
registerServiceWorker();
applyFullScreenFromSettings();
applyScreenOrientationFromSettings();
createRoot(document.getElementById("root")!).render(<App />);
scheduleAfterFirstPaint(startDeferredStartupBootstrap);
