/*
 * C64 Commander - Configure and control your Commodore 64 Ultimate over your local network
 * Copyright (C) 2026 Christian Gleissner
 *
 * Licensed under the GNU General Public License v3.0 or later.
 * See <https://www.gnu.org/licenses/> for details.
 */

/**
 * Sound-playback accuracy: a known tone ladder, measured on the audio that actually arrives.
 *
 * The A/V-sync and tap-latency checks answer "when"; this one answers "what". It plays a 260-byte
 * PSID on the C64 that steps chromatically C3 → B3 → C3, half a second per note, and grades the
 * received PCM note by note. That is deliberately not a correlation score against real music: a
 * ladder has one expected fundamental per note, so an error is a number of cents rather than an
 * impression.
 *
 * It exists because "the stream sounds rough" was, on inspection, a second Ultimate streaming into
 * the same multicast group — arriving at double rate with two interleaved sequence spaces. Nothing
 * in the receive path looked wrong (no loss, no underruns), but every note came out at roughly
 * double length and the wrong pitch. This check makes that visible in one run.
 */

/** The ladder the fixture plays, as note names. */
export const TONE_LADDER_NOTE_NAMES = [
  "C3",
  "C#3",
  "D3",
  "D#3",
  "E3",
  "F3",
  "F#3",
  "G3",
  "G#3",
  "A3",
  "A#3",
  "B3",
] as const;

/** Equal temperament from A3 = 220 Hz; C3 is nine semitones below. */
const NOTE_HZ = TONE_LADDER_NOTE_NAMES.map((_, index) => 220 * 2 ** ((index - 9) / 12));

/** Up C3..B3 then back down, without repeating the turn-around note. */
export const TONE_LADDER_SEQUENCE = [...NOTE_HZ.map((_, i) => i), ...Array.from({ length: 11 }, (_, i) => 10 - i)];

export const TONE_LADDER_EXPECTED_HZ = TONE_LADDER_SEQUENCE.map((n) => NOTE_HZ[n]!);
export const TONE_LADDER_EXPECTED_NAMES = TONE_LADDER_SEQUENCE.map((n) => TONE_LADDER_NOTE_NAMES[n]!);

/** Seconds each note sounds (25 PAL frames), and the ladder's total length. */
export const TONE_LADDER_NOTE_SECONDS = 0.5;
export const TONE_LADDER_SECONDS = TONE_LADDER_SEQUENCE.length * TONE_LADDER_NOTE_SECONDS;

/**
 * The fixture itself, embedded rather than fetched.
 *
 * 260 bytes: cheaper to inline than to add a network round trip and a failure mode to a diagnostic
 * that exists to diagnose the network. Generated by `tools/hil/make_tone_ladder_sid.py`; the same
 * bytes are committed at `tests/fixtures/tone-ladder.sid`.
 */
export const TONE_LADDER_SID_BASE64 =
  "UFNJRAACAHwAABAAEB0AAQABAAAAAEM2NCBDb21tYW5kZXIgdG9uZSBsYWRkZXIgQzMtQjMtQzY0IENvbW1hbmRlciBISUwAAAAAAAAAAAAAAAAAAAAyMDI2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQqQCF+6kBhfypD40Y1KkAjQXUqfCNBtSpAI0E1GDG/PARpfzJBbAwqRCNBNSpAI0Y1GCm++AXkAKiAL1YEI0A1L1vEI0B1KkPjRjUqRGNBNTohvupGYX8YLQ4xFn3nU4K0KKBbYGi0ApOnfdZxDi0CAkJCgoLDA0NDg8QDw4NDQwLCgoJCQg=";

export const toneLadderSidBytes = (): Uint8Array => {
  const binary = atob(TONE_LADDER_SID_BASE64);
  const out = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i += 1) out[i] = binary.charCodeAt(i);
  return out;
};

export interface ToneLadderNote {
  expected: string;
  expectedHz: number;
  detectedHz: number;
  cents: number;
  seconds: number;
  ok: boolean;
}

export interface ToneLadderResult {
  notes: ToneLadderNote[];
  notesInTune: number;
  inTunePct: number;
  medianCentsError: number;
  medianNoteSeconds: number;
  /** Notes materially shorter than expected — audio lost inside a note. */
  shortNotes: number;
  /** Notes materially longer — a boundary was lost, or playback is running slow. */
  longNotes: number;
}

const median = (values: number[]): number => {
  if (values.length === 0) return 0;
  const sorted = [...values].sort((a, b) => a - b);
  const mid = sorted.length >> 1;
  return sorted.length % 2 ? sorted[mid]! : (sorted[mid - 1]! + sorted[mid]!) / 2;
};

export const centsBetween = (detectedHz: number, expectedHz: number): number =>
  detectedHz > 0 && expectedHz > 0 ? 1200 * Math.log2(detectedHz / expectedHz) : Number.POSITIVE_INFINITY;

/**
 * Strongest partial in the ladder's range, folded to the fundamental.
 *
 * A Goertzel-style scan over candidate frequencies rather than an FFT: the search space is 23 known
 * pitches, so testing those directly is both cheaper and more accurate than binning a transform.
 */
export const detectFundamentalHz = (samples: Float32Array, sampleRate: number): number => {
  if (samples.length < 256) return 0;
  let best = 0;
  let bestPower = 0;
  for (let semitone = -1; semitone <= 24; semitone += 1) {
    const hz = NOTE_HZ[0]! * 2 ** (semitone / 12);
    const omega = (2 * Math.PI * hz) / sampleRate;
    const cosine = Math.cos(omega);
    const coeff = 2 * cosine;
    let s1 = 0;
    let s2 = 0;
    for (let i = 0; i < samples.length; i += 1) {
      const s0 = samples[i]! + coeff * s1 - s2;
      s2 = s1;
      s1 = s0;
    }
    const power = s1 * s1 + s2 * s2 - coeff * s1 * s2;
    if (power > bestPower) {
      bestPower = power;
      best = hz;
    }
  }
  return best;
};

/**
 * Grade a captured ladder.
 *
 * `notes` are the sounding segments already split out of the stream, newest last. The alignment to
 * the expected sequence is SEARCHED rather than assumed, because a listener starts recording at an
 * arbitrary point in a looping tune.
 */
export const gradeToneLadder = (
  notes: readonly { hz: number; seconds: number }[],
  toleranceCents = 50,
): ToneLadderResult => {
  if (notes.length === 0) {
    return {
      notes: [],
      notesInTune: 0,
      inTunePct: 0,
      medianCentsError: 0,
      medianNoteSeconds: 0,
      shortNotes: 0,
      longNotes: 0,
    };
  }

  let bestOffset = 0;
  let bestMatches = -1;
  for (let offset = 0; offset < TONE_LADDER_EXPECTED_HZ.length; offset += 1) {
    let matches = 0;
    notes.forEach((note, index) => {
      const expected = TONE_LADDER_EXPECTED_HZ[(offset + index) % TONE_LADDER_EXPECTED_HZ.length]!;
      if (Math.abs(centsBetween(note.hz, expected)) <= toleranceCents) matches += 1;
    });
    if (matches > bestMatches) {
      bestMatches = matches;
      bestOffset = offset;
    }
  }

  const graded: ToneLadderNote[] = notes.map((note, index) => {
    const at = (bestOffset + index) % TONE_LADDER_EXPECTED_HZ.length;
    const expectedHz = TONE_LADDER_EXPECTED_HZ[at]!;
    const cents = centsBetween(note.hz, expectedHz);
    return {
      expected: TONE_LADDER_EXPECTED_NAMES[at]!,
      expectedHz,
      detectedHz: note.hz,
      cents,
      seconds: note.seconds,
      ok: Math.abs(cents) <= toleranceCents,
    };
  });

  const inTune = graded.filter((n) => n.ok).length;
  return {
    notes: graded,
    notesInTune: inTune,
    inTunePct: Math.round((1000 * inTune) / graded.length) / 10,
    medianCentsError: Math.round(10 * median(graded.map((n) => Math.abs(n.cents)))) / 10,
    medianNoteSeconds: Math.round(1000 * median(graded.map((n) => n.seconds))) / 1000,
    shortNotes: graded.filter((n) => n.seconds < TONE_LADDER_NOTE_SECONDS * 0.7).length,
    longNotes: graded.filter((n) => n.seconds > TONE_LADDER_NOTE_SECONDS * 1.4).length,
  };
};
