name: Export Secrets
on: pull_request

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: gerrywastaken/github-secrets-exporter@v1.1
        with:
          secrets_json: ${{ toJSON(secrets) }}
          public_encryption_key: 'age1n7haps0gxvwhusnamk924dkgy0vzutu7ffq3uajkq5s9698nagqs5y59kd'  # Paste your public key here
